config/routes.rb
SampleApp::Application.routes.draw do
    resources :users do
        member do
            get :following, :followers
        end
        collection do
            get 'notify_user'
        end
    end

    resources :sessions,      only: [:new, :create, :destroy]

    resources :microposts,    only: [:create, :destroy, :index] do
        member do
            put 'approve'
            delete 'reject'
        end
    end

    resources :relationships, only: [:create, :destroy]

    root to: 'static_pages#home'

    match '/signup',  to: 'users#new',            via: 'get'
    match '/signin',  to: 'sessions#new',         via: 'get'
    match '/signout', to: 'sessions#destroy',     via: 'delete'
    match '/help',    to: 'static_pages#help',    via: 'get'
    match '/about',   to: 'static_pages#about',   via: 'get'
    match '/contact', to: 'static_pages#contact', via: 'get'
    match '/notifications', to: 'users#notifications', via: 'get'
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base

    belongs_to :user

    has_many :news_feeds

    default_scope -> { order('created_at DESC') }

    scope :published, -> { where(approved: true) }
    scope :pending, -> { where(approved: false) }

    validates :content, presence: true, length: { maximum: 140 }
    validates :user_id, presence: true

    after_create :send_notification_to_admin

    auto_html_for :content do
        html_escape
        image
        youtube(:width => 400, :height => 250, :autoplay => true)
        link :target => "_blank", :rel => "nofollow"
        simple_format
    end

    # Returns microposts from the users being followed by the given user.
    def self.from_users_followed_by(user)
        followed_user_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id" 
                            where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user.id)
    end

    def self.global_feed
        published.order("created_at DESC")
    end

    def send_notification_to_user
        micropost = self
        user = micropost.user
        unless user.blank?
            new_notification = user.news_feeds.create(content: "The Admin has approved your post. It will be visible to you and everyone",
                                                        feed_type: "Approved Post", micropost_id: micropost.id)
            # Libnotify.show(body: "Admin has approved your post. It should be visible now.", summary: "New Notification", timeout: 2.5)
        end
    end

    private

    def send_notification_to_admin
        User.where("admin IS ? ", true).each do |admin|
            # admin = User.find_by(admin: true)
            poster = self.user
            admin.news_feeds.create(content: "A new unpublished post. Please, review it.",
                                    micropost_id: self.id, feed_type: "Pending Post") unless poster.admin?
            # Libnotify.show(body: "#{poster.name} has a new unpublished post.", summary: "New Notification", timeout: 2.5) if !poster.admin?
        end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :signed_in_user, only: [:create, :destroy, :index, :approve]
    before_action :correct_user,   only: :destroy
    before_action :admin_user,     only: :reject


    def create
        @micropost = current_user.microposts.build(micropost_params)
        @micropost.toggle!(:approved) if current_user.admin?
        if @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
        else
            @feed_items = []
            render 'static_pages/home'
        end
    end

    def destroy
        @micropost = Micropost.find_by_id(params[:id])
        @micropost.destroy
        redirect_to root_url
    end

    def reject
        @micropost = Micropost.find_by_id(params[:id])
        @micropost.news_feeds.create(content: "Your post has been rejected. Thus, deleted from the system.", feed_type: "Rejected Post", user_id: @micropost.user_id) unless @micropost.user.admin?
        @micropost.destroy
        redirect_to microposts_path
    end

    def approve
        @micropost = Micropost.find_by_id(params[:id])
        @micropost.toggle!(:approved)
        flash[:success] = "Micropost Approved!"
        @micropost.send_notification_to_user
        redirect_to microposts_path
    end

    def index
        @pending_microposts = Micropost.pending.paginate(page: params[:page]) if current_user.admin?
        @published_microposts = Micropost.published.paginate(page: params[:page])
        respond_to do |format|
            format.html
        end
    end

    private

    def micropost_params
        params.require(:micropost).permit(:content)
    end

    def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
    end

    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end
end

app/views/microposts/_index.html.erb
<%- microposts.each do |micropost| -%>
	<li id="<%= micropost.id %>">
		<%= link_to gravatar_for(micropost.user), micropost.user %>
	   	<span class="user">
	       	<%= link_to micropost.user.name, micropost.user %>
	   	</span>
		<span class="content"><%= micropost.content %></span>
		<span class="timestamp">
		   	Posted <%= time_ago_in_words(micropost.created_at) %> ago.
	   	</span>
	   	<% if current_user.admin? && !current_user?(micropost.user) %>
	       	<%= link_to "Approve", approve_micropost_path(micropost), method: :put unless micropost.approved? %> | 
	       	<%= link_to "Reject", reject_micropost_path(micropost), method: :delete, data: { confirm: "You sure?" }, title: micropost.content %>
	   	<% end %>
	</li>
<%- end  -%>
<%= will_paginate microposts %>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content_html %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" }, title: micropost.content %>
  <% end %>
</li>

app/views/microposts/index.html.erb
<% if @pending_microposts.any? %>
	<h3>Pending</h3>
	<%= render "index", microposts: @pending_microposts  %>
<% end %>

<% if @published_microposts.any? %>
	<h3>Published</h3>
	<%= render "index", microposts: @published_microposts  %>
<% end %>